### ISSUE TITLE
.sentry.yml not working as intended

### ISSUE THREAD

**Issue by mfkp** [samueleaton/sentry#57]
Via the .sentry.yml.example file:

```yml
# The command used to compile the application. Setting this option to `nil` or
# an empty string will act like specifying `--no-build` on the command line.
build: crystal build ./src/sentry_cli.cr -o ./my-program-name
```

Setting this value to empty string or nil (and even deleting the build option from the yaml file) doesn't do anything. 

I think the bug comes in around here:

https://github.com/samueleaton/sentry/blob/master/src/sentry.cr#L71

It's switching to the default value of building ./src/(shardname).cr

Maybe this is a side effect from when PR #55 was merged?

**Comment by zw963** [comment]
Try on my fork https://github.com/crystal-china/sentry

it should be:

```yaml
build_command: crystal
build_args: build ./src/sentry_cli.cr -o ./my-program-name
run_command: ./my-program-name
```
